baseURL = "/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "example"
paginate = 3

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    pre = "<i class='fa fa-heart'></i>"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    post = "<span class='alert'>New!</span>"
    pre = "<i class='fa fa-road'></i>"
    url = "/blogs/"
    weight = 2

  [[menu.main]]
    name = "News"
    post = "<span class='alert'>New!</span>"
    pre = "<i class='fa fa-road'></i>"
    url = "/news/"
    weight = 3

[languages]
  [languages.en]
    title = ""
    subtitle = ""
    keywords = ""
    copyright = "@2019 Hugo Theme"
